# Generated by Django 5.2.7 on 2025-10-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Quadro')),
                ('cover_color', models.CharField(default='#ff7a7a', max_length=120, verbose_name='Cor/Gradiente')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do vídeo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('watched', models.BooleanField(default=False, verbose_name='Assistido')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.quadro')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
